[tox]
envlist = py{38,39,310}-{linux,macos,windows}, black, flake8, isort, mypy
requires =
  tox-gh-actions

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310, black, flake8, isort, mypy

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

[testenv:black]
description = run black with check-only under {basepython}
commands = black --check {{ cookiecutter.project_slug }}/ tests/ setup.py
extras = testing

[testenv:flake8]
description = run flake8 under {basepython}
deps = flake8
commands = flake8 {{ cookiecutter.project_slug }}/ tests/

[testenv:isort]
description = run isort under {basepython}
deps = isort
commands = isort {{ cookiecutter.project_slug }}/ tests/

[testenv:mypy]
description = run mypy under {basepython}
deps = mypy
commands = mypy {{ cookiecutter.project_slug }}/

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pip install -U pip
    pytest --cov=tox_gh_actions --cov-branch --cov-report=term --cov-report=xml {posargs}

