repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: tests\/test_{{cookiecutter.project_slug}}\.py
  - repo: https://github.com/pycqa/flake8
    rev:  5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--exclude", "E402"]
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
        args:
          - --unsafe
        exclude: "not_rendered.yml|invalid-config.yaml"
      - id: trailing-whitespace
