name: CI
on:
  push:
    branches: [master, main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  ## Sets linting variables
  PYTHON_BLACK_CONFIG_FILE: pyproject.toml
  PYTHON_FLAKE8_CONFIG_FILE: .flake8
  PYTHON_ISORT_CONFIG_FILE: pyproject.toml
  VALIDATE_PYTHON_ISORT: true
  VALIDATE_PYTHON_FLAKE8: true
  VALIDATE_PYTHON_BLACK: true
  FILTER_REGEX_EXCLUDE: .*tests/.*
  LINTER_RULES_PATH: /
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Super Linter for isort,black and flake8
        uses: github/super-linter@v4.9.5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start container and run tests
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            directory: ./coverage/reports/
            fail_ci_if_error: true
            flags: unittests
            name: codecov-umbrella
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true
      - name: Stop containers
        run: make stop
