jobs:
  toxify:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tests with tox
          command: tox
      - store_artifacts:
          path: htmlcov
workflows:
  version: 2
  test-workflow:
    jobs:
      - toxify
